### PR TITLE
/home/notes/create, /home/notes/today, /progress/summary, /progress/ - mark_a_day, /progress/ - read_relapses

### PR DESCRIPTION
**Pull request by TaslimOwolarafe**
added user field to note model, fixed endpoints accordingly. 

response data contracts on these endpoints have been changed to form:

{
  "status": "success",
  "message": "note created",
  "data": {
    "id": 4,
    "title": "Sample",
    "created_at": "2022-12-08T03:25:33.591066",
    "user": 1,
    "description": "this is an example.",
    "updated_at": "2022-12-08T03:25:33.591066"
  }
}

### CODE REVIEW

**Comment by seyipaye** [comment]
Please resolve your conflict

**Comment by TaslimOwolarafe** [comment]
> 

It says okay, is it there?

**Comment by seyipaye** [comment]
Screenshot 2022-12-08 at 16 16 27

**Comment by seyipaye** [comment]
Please check it again my boss
Pull from dev

**Pull request merged**
